language: node_js
node_js:
  - 10
cache:
  npm: true # this caches ~/.npm folder on Travis
  directories:
    #need to cache folder with Cypress binary
    - ~/.cache
install:
  - npm install
script:
  - $(npm bin)/cypress run --record --key c116646d-bfdd-47b6-93b8-d77e56bd8719