language: node_js
node_js:
- 10
cache:
  npm: true
  directories:
  - "~/.cache"
install:
- npm install
script:
- "$(npm bin)/cypress run --record --key c116646d-bfdd-47b6-93b8-d77e56bd8719"
env:
  secure: oEdKHa9ie+GLxnMTYzBGy3Pahsu2qun2RZWhLYzi1SHARlO1ZEzMclJTbb6xDqf/sHCPQKlvRZLsbpFR4f4wmrUQdt7EBA66Wkjc4TyyS5HrTtzJYgVp3X1FI+76SHH3EKIIsTDxbYbhqS6CwS1JsXTRayzqwo8ecgu9lAEaFphgMCV8Ltle5ujQJjqan3er0m7z9aJa4BxzY9FiAi8UJZI6mBgAIV5mWTmI+EMHxkn6AJijhasoBRI37HY5t95Ofr2Xy8ey+OCJCzlVcygW6qdrQATB7+YnWsCuQqg8uhX60AfbtJUPpQO3+vyzH0z8MaE/FxD7RF7Vm+ZUietg4+kF/ACTgzEq4ARQ5OUifVk6DCSWi6vDByp/Iz2KAWv3l14nsfgipO6hbj2bqqn13JxUbXp0gG8fRV9ICAYf0FQbGkxf8gW1sa2ocr1rPspEtBBoKRwoR8NlgC5ybqIC9tDqTm9fDZV48xZfWATB0uAv42h9vbdKhtTHptuUsvgkKmKMcTl4cmF49ivXhedC+yHixXLGlRNVuB4YhAUu8nJG0mAVSlYj5pR2LmeoQpGgI3aG59D28yoU8E3g/rtPQGh7+GJE8AIINNtiKR61xszRBpVkDgiQ2/n8wd3MYb/t0/i7rHzPZmHTHt1CA/Dakn/AHaQAVaF6o4jciLHj9GI=
